export type Language = 'zh-CN' | 'en-US';

export const languageStorageKey = 'apple-connector.management.language';

const zh = {
  localManagement: '仅限本机管理', managementSession: '管理会话', expires: '过期时间', sessionExpired: '管理会话已过期。请重新运行', loadingSession: '正在加载管理会话…', languageSelector: '界面语言',
  permissions: '权限', agentProfiles: 'Agent 配置', approvals: '审批', audit: '审计', systemPermissions: '系统权限', permissionsDescription: 'macOS 权限与 Agent 授权相互独立。此页面会在打开时检查当前原生状态，并只在你点击时请求系统访问。',
  requestCalendar: '请求日历权限', requestReminders: '请求提醒事项权限', permissionsHelp: '若访问被拒绝或受限，请前往“系统设置 → 隐私与安全性”修改权限，然后重新打开此页面并重试。', permissionStatus: '权限状态', lastChecked: '最近检查', checking: '正在检查系统权限…', unavailable: '无法检查', fullAccess: '已获完全访问', writeOnly: '仅写入访问', denied: '已拒绝', restricted: '受系统限制', notDetermined: '尚未决定', unknown: '未知状态',
  createAgentProfile: '创建 Agent 配置', existingAgentProfiles: '已有 Agent 配置', profilesGroupedByName: '按配置名称聚合；每个凭据和授权仍独立。', credential: '凭据配置', activeProfiles: (count: number) => `${count} 个启用`, revokedProfiles: (count: number) => `${count} 个已撤销`, profileDescription: '请选择确切可见的容器。稳定的 EventKit ID 会自动保存；凭证仅写入所有者可读的本机文件，且绝不会展示。', defaultProfileName: '我的 Agent', name: '名称', provider: '服务', calendar: '日历', reminders: '提醒事项', allowedContainers: '允许的容器', noContainers: '没有可见容器。请先在上方请求系统权限，然后重试。', allowedActions: '允许的操作', read: '读取', create: '创建', update: '更新', complete: '完成', delete: '删除', calendarFields: '日历字段', full: '完整内容', busyOnly: '仅忙碌状态', writes: '写入', requireApproval: '需要审批', automaticWithinScope: '在授权范围内自动执行', expiresAt: '过期时间', createProfile: '创建配置', state: '状态', policy: '策略', action: '操作', revoke: '撤销', revoked: '已撤销', active: '启用', noProfiles: '还没有 Agent 配置。创建一个受限 profile 以开始。', grant: '授权', scope: '范围', fields: '字段', approval: '审批',
  pendingOperations: '待审批操作', approvalDescription: '审批仅适用于已持久化且不可变的操作。', operation: '操作', approve: '批准', reject: '拒绝', noPendingOperations: '当前没有等待审批的操作。', auditDescription: '审计记录仅包含元数据，不会保留标题、正文、备注或凭证。', time: '时间', outcome: '结果', count: '数量', noAuditEvents: '还没有审计记录。',
  configurationComplete: '配置完成。请返回 Agent 并回复：已完成。', profileCreated: (path: string) => `配置已创建。凭证保存于 ${path}。仅向 Agent 提供该路径，切勿提供其内容。`, couldNotOpen: '无法打开管理会话。', couldNotList: '无法列出容器。', couldNotCreate: '无法创建配置。', couldNotUpdate: '无法更新操作。',
};

const en = {
  localManagement: 'Local management only', managementSession: 'Management session', expires: 'Expires', sessionExpired: 'Management session expired. Run', loadingSession: 'Loading management session…', languageSelector: 'Language',
  permissions: 'Permissions', agentProfiles: 'Agent profiles', approvals: 'Approvals', audit: 'Audit', systemPermissions: 'System permissions', permissionsDescription: 'macOS permission and Agent grants are separate. This page checks the current native status when it opens and requests system access only when you choose to.',
  requestCalendar: 'Request Calendar permission', requestReminders: 'Request Reminders permission', permissionsHelp: 'If access is denied or restricted, change it in System Settings → Privacy & Security, then reopen this page and retry.', permissionStatus: 'Permission status', lastChecked: 'Last checked', checking: 'Checking system permissions…', unavailable: 'Could not check', fullAccess: 'Full access granted', writeOnly: 'Write-only access', denied: 'Denied', restricted: 'Restricted by system', notDetermined: 'Not determined', unknown: 'Unknown status',
  createAgentProfile: 'Create your Agent profile', existingAgentProfiles: 'Existing Agent profiles', profilesGroupedByName: 'Grouped by profile name; every credential and grant remains independent.', credential: 'Credential profile', activeProfiles: (count: number) => `${count} active`, revokedProfiles: (count: number) => `${count} revoked`, profileDescription: 'Select the exact visible containers. Stable EventKit IDs are saved automatically; the credential is written to an owner-only local file and never displayed.', defaultProfileName: 'My Agent', name: 'Name', provider: 'Provider', calendar: 'Calendar', reminders: 'Reminders', allowedContainers: 'Allowed containers', noContainers: 'No visible containers. Request system permission above, then retry.', allowedActions: 'Allowed actions', read: 'Read', create: 'Create', update: 'Update', complete: 'Complete', delete: 'Delete', calendarFields: 'Calendar fields', full: 'Full', busyOnly: 'Busy only', writes: 'Writes', requireApproval: 'Require approval', automaticWithinScope: 'Automatic within scope', expiresAt: 'Expires', createProfile: 'Create profile', state: 'State', policy: 'Policy', action: 'Action', revoke: 'Revoke', revoked: 'revoked', active: 'active', noProfiles: 'No Agent profiles yet. Create a limited profile to get started.', grant: 'Grant', scope: 'Scope', fields: 'Fields', approval: 'Approval',
  pendingOperations: 'Pending operations', approvalDescription: 'Approval applies only to the already-persisted immutable operation.', operation: 'Operation', approve: 'Approve', reject: 'Reject', noPendingOperations: 'No operations are waiting for approval.', auditDescription: 'Audit records are metadata-only. They do not retain titles, bodies, notes, or credentials.', time: 'Time', outcome: 'Outcome', count: 'Count', noAuditEvents: 'No audit events yet.',
  configurationComplete: 'Configuration complete. Return to your Agent and reply: done.', profileCreated: (path: string) => `Profile created. Credential saved to ${path}. Give an agent only this path, never its contents.`, couldNotOpen: 'Could not open management session.', couldNotList: 'Could not list containers.', couldNotCreate: 'Could not create profile.', couldNotUpdate: 'Could not update operation.',
};

export const translations = { 'zh-CN': zh, 'en-US': en } as const;

export function resolveLanguage(value: string | null | undefined): Language { return value === 'en-US' ? 'en-US' : 'zh-CN'; }
export function readLanguagePreference(storage: Pick<Storage, 'getItem'> | undefined): Language { try { return resolveLanguage(storage?.getItem(languageStorageKey)); } catch { return 'zh-CN'; } }
export function saveLanguagePreference(storage: Pick<Storage, 'setItem'> | undefined, language: Language): void { try { storage?.setItem(languageStorageKey, language); } catch { /* A blocked storage preference must not prevent management access. */ } }
export function formatDate(value: number, language: Language): string { return new Date(value).toLocaleString(language); }
