import { ConnectorError } from '../../application/errors.js';
import { EventKitHelperClient } from '../../native/helper-client.js';
import type { CalendarContainer, CalendarEvent, CalendarPage } from './jxa-reader.js';
export interface CalendarReader { listCalendars(containerIds: string[]): Promise<CalendarContainer[]>; listEvents(calendarId: string, from: string, to: string, offset?: number, limit?: number): Promise<CalendarPage>; }
function record(value: unknown): Record<string, unknown> { if (!value || typeof value !== 'object') throw new ConnectorError('protocol_error', 'EventKit helper returned invalid data.'); return value as Record<string, unknown>; }
export class EventKitCalendarReader implements CalendarReader {
  constructor(private readonly helper: EventKitHelperClient) {}
  async listCalendars(containerIds: string[]): Promise<CalendarContainer[]> { const value = await this.helper.call('calendar.listCalendars', { containerIds }); if (!Array.isArray(value)) throw new ConnectorError('protocol_error', 'EventKit helper returned invalid calendars.'); return value.map((x) => { const r = record(x); if (typeof r.id !== 'string' || typeof r.name !== 'string') throw new ConnectorError('protocol_error', 'EventKit helper returned invalid calendar.'); return { id: r.id, name: r.name }; }); }
  async listEvents(calendarId: string, from: string, to: string, offset = 0, limit = 50): Promise<CalendarPage> { const r = record(await this.helper.call('calendar.listEvents', { calendarId, from, to, offset, limit })); if (!Array.isArray(r.items) || (r.nextOffset !== null && (!Number.isInteger(r.nextOffset) || typeof r.nextOffset !== 'number'))) throw new ConnectorError('protocol_error', 'EventKit helper returned invalid page.'); const items: CalendarEvent[] = r.items.map((x) => { const e = record(x); if (e.calendarId !== calendarId || typeof e.title !== 'string' || typeof e.start !== 'string' || typeof e.end !== 'string' || typeof e.allDay !== 'boolean' || typeof e.location !== 'string' || typeof e.notes !== 'string' || Date.parse(e.end) <= Date.parse(e.start)) throw new ConnectorError('protocol_error', 'EventKit helper returned invalid event.'); return e as unknown as CalendarEvent; }); return { items, nextOffset: r.nextOffset as number | null }; }
}
